version: 2.1

jobs:
  build-and-test:
    docker:
        - image: busybox
    steps:
      - run:
          name: Hello World
          command: |
            echo "Hello World"

workflows:
  main:
    jobs:
      - build-and-test
