version: 2.1

jobs:
  build_and_deploy:
    docker:
        - image: google/cloud-sdk:slim
    steps:
      - checkout
      - run:
          name: Install Sphinx
          command: |
            apt install -y python-pip && \
            python3 -m pip install -r requirements.txt
      - run:
          name: Make Docs
          command: |
            cd docs && make html

workflows:
  main:
    jobs:
      - build_and_deploy
